// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to  DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.
// 
// 
// 

#region

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading;
using WinterLeaf.Classes;
using WinterLeaf.Containers;
using WinterLeaf.Enums;
using WinterLeaf.tsObjects;

#endregion

namespace DNT_FPS_Demo_Game_Dll.Tools
{
    //-----------------------------------------------------------------------------
    // AIPlayer callbacks
    // The AIPlayer class implements the following callbacks:
    //
    //    PlayerData::onStop(%this,%obj)
    //    PlayerData::onMove(%this,%obj)
    //    PlayerData::onReachDestination(%this,%obj)
    //    PlayerData::onMoveStuck(%this,%obj)
    //    PlayerData::onTargetEnterLOS(%this,%obj)
    //    PlayerData::onTargetExitLOS(%this,%obj)
    //    PlayerData::onAdd(%this,%obj)
    //
    // Since the AIPlayer doesn't implement it's own datablock, these callbacks
    // all take place in the PlayerData namespace.
    //-----------------------------------------------------------------------------

    //-----------------------------------------------------------------------------
    // BaseCanvas
    //-----------------------------------------------------------------------------
    public partial class Main : TorqueScriptTemplate
    {
        [Torque_Decorations.TorqueCallBack("", "BaseEditorCanvas", "onAdd", "", 1, 2500, false)]
        public void BaseEditorCanvasOnAdd(coGuiCanvas thisObj)
        {
            BaseEditorCanvasCreateMenuBar(thisObj);
            coGuiPanel panel;
            Torque_Class_Helper TCH = new Torque_Class_Helper("GuiPanel");
            TCH.PropsAddString("internalName", "DocumentContainer");
            panel = TCH.Create();
            thisObj.setContent(panel);
            int xOffset = 20;
            int yOffset = 20;
            for (int i = 0; i < 10; i++)
            {
                coGuiWindowCtrl window;
                TCH = new Torque_Class_Helper("GuiWindowCtrl");
                TCH.Props.Add("extent", "200 100");
                TCH.Props.Add("position", xOffset + " " + yOffset);
                window = TCH.Create();
                panel.add(window);
                xOffset += 30;
                yOffset += 30;
            }
        }

        [Torque_Decorations.TorqueCallBack("", "BaseEditorCanvas", "onRemove", "", 1, 2500, false)]
        public void BaseEditorCanvasOnRemove(coGuiCanvas thisObj)
        {
            BaseEditorCanvasDestroyMenuBar(thisObj);
        }
    }
}
